language: cpp

os: linux
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

matrix:
  include:
    - env: BUILD_TYPE=check
    - compiler: gcc
      env: BUILD_TYPE=codecov
    - compiler: clang
      env: BUILD_TYPE=normal

before_script:
  - util/travis_before_script.sh
script:
  - util/travis_script.sh
after_success:
  - util/travis_after_success.sh

notifications:
  irc:
    channels: "chat.freenode.net#banditcpp"
    skip_join: true
    use_notice: true
    template: "%{repository} %{branch} (%{commit} %{commit_subject} -- %{author}): %{message} See %{compare_url}"
